import type { Template } from '../types';

export const funeralTemplates: Template[] = [
  {
    name: 'Serene Sky',
    primaryColor: '#0369A1',
    fontFamily: 'serif',
    backgroundColor: '#F0F9FF',
    textColor: '#082F49',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Sunset Peace',
    primaryColor: '#EA580C',
    fontFamily: 'sans-serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Woodland Floral',
    primaryColor: '#166534',
    fontFamily: 'sans-serif',
    backgroundColor: '#F0FDF4',
    textColor: '#14532D',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Solemn Chapel',
    primaryColor: '#F97316',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Coastal Farewell',
    primaryColor: '#EA580C',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Mountain Majesty',
    primaryColor: '#57534E',
    fontFamily: 'sans-serif',
    backgroundColor: '#FAFAF9',
    textColor: '#292524',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Starlight Goodbye',
    primaryColor: '#4338CA',
    fontFamily: 'sans-serif',
    backgroundColor: '#EEF2FF',
    textColor: '#312E81',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Garden of Memories',
    primaryColor: '#DB2777',
    fontFamily: 'serif',
    backgroundColor: '#FEF1F2',
    textColor: '#831843',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Modern Abstract',
    primaryColor: '#4B5563',
    fontFamily: 'serif',
    backgroundColor: '#F3F4F6',
    textColor: '#111827',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Vintage Tribute',
    primaryColor: '#78350F',
    fontFamily: 'sans-serif',
    backgroundColor: '#FEFCE8',
    textColor: '#422006',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Pastel Horizon',
    primaryColor: '#0369A1',
    fontFamily: 'serif',
    backgroundColor: '#F0F9FF',
    textColor: '#082F49',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Earthen Sunset',
    primaryColor: '#EA580C',
    fontFamily: 'sans-serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Royal Forest',
    primaryColor: '#166534',
    fontFamily: 'sans-serif',
    backgroundColor: '#F0FDF4',
    textColor: '#14532D',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Crimson Church',
    primaryColor: '#F97316',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Azure Beach',
    primaryColor: '#EA580C',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Monochrome Peaks',
    primaryColor: '#57534E',
    fontFamily: 'sans-serif',
    backgroundColor: '#FAFAF9',
    textColor: '#292524',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Golden Cosmos',
    primaryColor: '#4338CA',
    fontFamily: 'sans-serif',
    backgroundColor: '#EEF2FF',
    textColor: '#312E81',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Pastel Blooms',
    primaryColor: '#DB2777',
    fontFamily: 'serif',
    backgroundColor: '#FEF1F2',
    textColor: '#831843',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Abstract Earth',
    primaryColor: '#65A30D',
    fontFamily: 'serif',
    backgroundColor: '#F7FEE7',
    textColor: '#365314',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Vintage Royal',
    primaryColor: '#78350F',
    fontFamily: 'sans-serif',
    backgroundColor: '#FEFCE8',
    textColor: '#422006',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.90rem',
  },
  {
    name: "Sky's Embrace",
    primaryColor: '#0369A1',
    fontFamily: 'serif',
    backgroundColor: '#F0F9FF',
    textColor: '#082F49',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Sunset Vista',
    primaryColor: '#EA580C',
    fontFamily: 'sans-serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Forest Sanctuary',
    primaryColor: '#166534',
    fontFamily: 'sans-serif',
    backgroundColor: '#F0FDF4',
    textColor: '#14532D',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Hallowed Halls',
    primaryColor: '#F97316',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Seaside Serenity',
    primaryColor: '#EA580C',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Mountain Echoes',
    primaryColor: '#57534E',
    fontFamily: 'sans-serif',
    backgroundColor: '#FAFAF9',
    textColor: '#292524',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Celestial Journey',
    primaryColor: '#4338CA',
    fontFamily: 'sans-serif',
    backgroundColor: '#EEF2FF',
    textColor: '#312E81',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Tranquil Garden',
    primaryColor: '#DB2777',
    fontFamily: 'serif',
    backgroundColor: '#FEF1F2',
    textColor: '#831843',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Bold Expression',
    primaryColor: '#4B5563',
    fontFamily: 'serif',
    backgroundColor: '#F3F4F6',
    textColor: '#111827',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Timeless Classic',
    primaryColor: '#78350F',
    fontFamily: 'sans-serif',
    backgroundColor: '#FEFCE8',
    textColor: '#422006',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Gentle Clouds',
    primaryColor: '#0369A1',
    fontFamily: 'serif',
    backgroundColor: '#F0F9FF',
    textColor: '#082F49',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Warm Horizon',
    primaryColor: '#EA580C',
    fontFamily: 'sans-serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Verdant Woods',
    primaryColor: '#166534',
    fontFamily: 'sans-serif',
    backgroundColor: '#F0FDF4',
    textColor: '#14532D',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Sacred Space',
    primaryColor: '#F97316',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Oceanic Rest',
    primaryColor: '#EA580C',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Alpine Stillness',
    primaryColor: '#57534E',
    fontFamily: 'sans-serif',
    backgroundColor: '#FAFAF9',
    textColor: '#292524',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Guiding Stars',
    primaryColor: '#4338CA',
    fontFamily: 'sans-serif',
    backgroundColor: '#EEF2FF',
    textColor: '#312E81',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Perennial Love',
    primaryColor: '#DB2777',
    fontFamily: 'serif',
    backgroundColor: '#FEF1F2',
    textColor: '#831843',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Minimalist Honor',
    primaryColor: '#4B5563',
    fontFamily: 'serif',
    backgroundColor: '#F3F4F6',
    textColor: '#111827',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Golden Age',
    primaryColor: '#78350F',
    fontFamily: 'sans-serif',
    backgroundColor: '#FEFCE8',
    textColor: '#422006',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Pastel Heavens',
    primaryColor: '#0369A1',
    fontFamily: 'serif',
    backgroundColor: '#F0F9FF',
    textColor: '#082F49',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Earthen Glow',
    primaryColor: '#EA580C',
    fontFamily: 'sans-serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Regal Grove',
    primaryColor: '#166534',
    fontFamily: 'sans-serif',
    backgroundColor: '#F0FDF4',
    textColor: '#14532D',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Blessed Sanctuary',
    primaryColor: '#F97316',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Coastal Calm',
    primaryColor: '#EA580C',
    fontFamily: 'serif',
    backgroundColor: '#FFF7ED',
    textColor: '#7C2D12',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Stone Monument',
    primaryColor: '#57534E',
    fontFamily: 'sans-serif',
    backgroundColor: '#FAFAF9',
    textColor: '#292524',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '2.0rem',
    h2Size: '1.5rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Starlit Path',
    primaryColor: '#4338CA',
    fontFamily: 'sans-serif',
    backgroundColor: '#EEF2FF',
    textColor: '#312E81',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.9rem',
    h2Size: '1.4rem',
    bodySize: '0.90rem',
  },
  {
    name: 'Evergreen Memory',
    primaryColor: '#DB2777',
    fontFamily: 'serif',
    backgroundColor: '#FEF1F2',
    textColor: '#831843',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.8rem',
    h2Size: '1.3rem',
    bodySize: '0.85rem',
  },
  {
    name: 'Modern Grace',
    primaryColor: '#4B5563',
    fontFamily: 'serif',
    backgroundColor: '#F3F4F6',
    textColor: '#111827',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.7rem',
    h2Size: '1.2rem',
    bodySize: '0.95rem',
  },
  {
    name: 'Grand Vintage',
    primaryColor: '#78350F',
    fontFamily: 'sans-serif',
    backgroundColor: '#FEFCE8',
    textColor: '#422006',
    headerPaddingTop: '1.5rem',
    headerPaddingBottom: '1.5rem',
    footerPadding: '1rem',
    h1Size: '1.6rem',
    h2Size: '1.1rem',
    bodySize: '0.90rem',
  },
];
